### ISSUE TITLE
Glue Catalog compatible materialization

### ISSUE THREAD

**Issue by wrborigin** [starburstdata/dbt-trino#26]
I have an idea for a feature and wonder if it makes sense to be part of dbt-trino or not.

Trino is commonly deployed on AWS with AWS Glue Catalog - you see people referencing it a lot. AWS Glue Catalog doesn't support renaming tables, so normal `table` materialization doesn't work. So anyone using Trino, dbt and Glue has to override the materialization macro to be able to materialize tables.

The way we do this is we just move things around so that instead of create new, rename old, rename new, drop old we just do drop old, create new. That causes table to be unavailable for a period of time, but works as a quick fix. Also we have to maintain our custom macro, and ship it with every dbt project.

Could this be looked at as part of dbt-trino? maybe creating official "table_norename" materialization, or looking into materialized views, insert overwrite or something? It would make lives of everyone using Trino with AWS much easier.

**Comment by findinpath** [comment]
I tried using `dbt-trino` on top of Trino by having the hive connector set to work with glue settings.

This is my `etc/catalogs/hive.properties` file content:

```
connector.name=hive

hive.metastore=glue
hive.metastore.glue.region=eu-central-1
hive.metastore.glue.aws-access-key=${ENV:HIVE_S3_ACCESS_KEY}
hive.metastore.glue.aws-secret-key=${ENV:HIVE_S3_SECRET_KEY}
hive.s3.endpoint=https://s3.eu-central-1.amazonaws.com
hive.s3.aws-access-key=${ENV:HIVE_S3_ACCESS_KEY}
hive.s3.aws-secret-key=${ENV:HIVE_S3_SECRET_KEY}
hive.s3.path-style-access=false
hive.non-managed-table-writes-enabled=true


hive.allow-drop-table=true
hive.allow-rename-table=true
```


When trying to run the statement

```
alter table "hive"."glue"."stg_customer__dbt_tmp" rename to "hive"."glue"."stg_customer"
```

I am encountering the following issue:


```
io.trino.spi.TrinoException: Table rename is not yet supported by Glue service
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.renameTable(GlueHiveMetastore.java:664)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.renameTable(CachingHiveMetastore.java:562)
	at io.trino.plugin.hive.HiveMetastoreClosure.renameTable(HiveMetastoreClosure.java:170)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$renameTable$13(SemiTransactionalHiveMetastore.java:511)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1171)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3026)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:225)
	at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:613)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_363_e____20211220_113008_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findinpath** [comment]
@wrborigin thank you for bringing this problem to our attention.

As already documented, AWS Glue doesn't support table renames which are currently at the core of the `dbt` functionality.

Performing the `table` materialization in a custom manner for `dbt-trino` when dealing with AWS Glue is actually not something that can be easily done AFAIK. 

`dbt-trino` actually doesn't know about the underlying details of the database sitting behind Trino.


Moreover doing the rename from TOld to TNew as you suggested (if i understand correctly) in the following manner:

- perform a CTAS (create table as select) from TOld  into TNew
- drop TOld

would mean dealing with two operations - which is not atomic. 
This can leave the system in an inconsistent state. For this reason, I think this is not something `dbt-trino` should support.

However, if you have the need to implement this functionality on your project, you can opt for a custom dbt materialization to encode this behavior.

https://docs.getdbt.com/docs/guides/creating-new-materializations

**Comment by hovaesco** [comment]
Take a look how the issue was handled https://github.com/starburstdata/dbt-trino#materialization.
