### ISSUE TITLE
Inserts not working with seeds and typed columns

### ISSUE THREAD

**Issue by mdesmet** [starburstdata/dbt-trino#42]
When using seed files and running `dbt seed`, the generated insert sql is not working as types are not specified.

For example a seed file with following contents:

data_date_trunc.csv
```
updated_at,day,month
2018-01-05 12:00:00,2018-01-05,2018-01-01
,,
```

with following config in dbt_project.yml

```
seeds:
    data_date_trunc:
      +column_types:
        updated_at: timestamp(3)
        day: date
        month: date
```

Creates following create table statements

```
CREATE TABLE memory.default.data_date_trunc (
   updated_at timestamp(3),
   day date,
   month date
)
```

Following insert is generated

```
insert into "memory"."default"."data_date_trunc" (updated_at, day, month) values
          ('2018-01-05 12:00:00','2018-01-05','2018-01-01'),(NULL,NULL,NULL)
```

which fails with 

```
io.trino.spi.TrinoException: Insert query has mismatched column types: Table: [timestamp(3), date, date], Query: [varchar(19), varchar(10), varchar(10)]
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:533)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:404)
	at io.trino.sql.tree.Insert.accept(Insert.java:68)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:254)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:179)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:776)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_369____20220206_204929_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

More examples can be run through running the the tests on https://github.com/innoverio/dbt-trino-utils

**Comment by findinpath** [comment]
dbt_project.yml
```
seeds:

  data_date_trunc:
    +column_types:
      updated_at: timestamp(3)
      day: date
      month: date
```


data/data_date_trunc.sql
```
updated_at,day,month
2018-01-05 12:00:00,2018-01-05,2018-01-01
NULL,NULL,NULL
```

output of `dbt seed`
```
create table "memory"."default"."data_date_trunc" ("id" INTEGER,"user_id" INTEGER,"order_date" DATE,"status" VARCHAR)
insert into "memory"."default"."data_date_trunc" ("updated_at", "day", "month") values
          (TIMESTAMP '2018-01-05 12:00:00.000',DATE '2018-01-05',DATE '2018-01-01'),(NULL,NULL,NULL)
```

Works as expected I would say.

Please provide more details on how to reproduce the issue.

**Comment by mdesmet** [comment]
Good news indeed, i restarted the trino db, and now it succeeded. I must have been looking at an old insert entry.

**Comment by mdesmet** [comment]
I'm able to reproduce the issue by adding a column type specification.

```
seeds:
  test_project: 
    cross_db:
      data_date_trunc2:
        +column_types:
          updated_at: timestamp
          day: date
          month: date
```

I've also added some test project to demonstrate the issue: [test_project.zip](https://github.com/starburstdata/dbt-trino/files/8018376/test_project.zip)
